name: bao
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - joblib=1.2.0
  - numpy=1.23.5
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - pip:
    - psycopg2==2.9.5
    - torch==1.13.0+cpu
    - threadpoolctl==3.1.0
    - typing-extensions==4.4.0